# Generated by Django 5.2.9 on 2025-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(db_column='id_alerta', primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_estacion', models.AutoField(db_column='id_estacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('certificado', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'estacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(db_column='id_institucion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('set_colores', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.AutoField(db_column='id_medicion', primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id_sensor', models.AutoField(db_column='id_sensor', primary_key=True, serialize=False)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudEstacion',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('certificado', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'solicitud_estacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudInstitucion',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=500, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'solicitud_institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.CharField(max_length=300, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id_variable', models.AutoField(db_column='id_variable', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'variable',
                'managed': False,
            },
        ),
    ]
